# Generated by Django 3.1.7 on 2021-05-03 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210331_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(220)]),
        ),
    ]
