# Generated by Django 3.1.7 on 2021-05-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210512_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travellingform', models.CharField(max_length=20, null=True)),
                ('travellingto', models.CharField(max_length=20, null=True)),
                ('departing', models.DateTimeField(null=True)),
                ('returing', models.DateTimeField(null=True)),
                ('adults', models.IntegerField(null=True)),
                ('childern', models.IntegerField(null=True)),
                ('traveltypes', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
