# Generated by Django 3.1.7 on 2021-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210519_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='lowerclass',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='upperclass',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
